### ISSUE TITLE
[Feature request] Remember sort options from previous session

### ISSUE THREAD

**Issue by wonx** [gameyfin/gameyfin#277]
**Is your feature request related to a problem? Please describe.**
By default, Gameyfin sorts games by title, alphabetically. Personally, I like it to show newer games first.

**Describe the solution you'd like**
Gameyfin could remember the last sort/filter options that were used and apply those when the page loads.

**Describe alternatives you've considered**
An alternative would be to have an option in the settings to select the default sort and filter options.

**Comment by grimsi** [comment]
I currently don't accept new feature requests, but a solution for you could be to bookmark the URL including the sort parameter: https://gameyfin.url/library?sort=releaseDate_desc
