### ISSUE TITLE
Windows Baremetal won't start

### ISSUE THREAD

**Issue by notdeers** [gameyfin/gameyfin#433]
**Describe the bug**
Upon attempting to run the jar file through windows command line, the program fails.

**To Reproduce**
1. Go to command line
2. run cd C:\Program Files\Java\jdk-21\ 
3. run java -jar C:\Users\gnofl\Documents\Gameyfin\gameyfin.jar debug
4. See screenshots of error

**Expected behavior**
Program starts

**Screenshots**
![image](https://github.com/user-attachments/assets/c4cc3ab6-5e78-4f39-b96b-9cb39fc2b5d7)
![image](https://github.com/user-attachments/assets/56e19ed6-4734-4487-876e-5774e4cfc11d)

**General info (please complete the following information):**
 - Installation method: Bare Metal
 - Java version (if installation method is "bare metal"): JDK 21
 - Browser (if bug is in the Web UI) [e.g. chrome, safari]: N/A
 - Gameyfin version: 1.4.6

**Additional context**
There appear to be 4 main errors, which I copied below. All of them seem to focus on the "springframework" except for the last one which says I still have a place holder for gameyfin.sources but I edited the properties file to have gameyfin.sources=C:\\Users\\gnofl\\Documents\\Gameyfin so I can't see why it'd be claiming it's a placeholder. I also tried using a folder C:\\Gameyfin which also failed.
I'm very new to java, so this could just be me missing something simple, but I followed the set-up instructions exactly. Any advice would be helpful.

Main Errors: 

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception with message: Error creating bean with name 'gameyfinFolderConfig': Injection of autowired dependencies failed

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception with message: Error creating bean with name 'gameyfinFolderConfig': Injection of autowired dependencies failed

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gameyfinFolderConfig': Injection of autowired dependencies failed

Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'gameyfin.sources' in value "#{'${gameyfin.sources}'.split(',')[0]}"

**Comment by grimsi** [comment]
Hi, thanks for your detailed report!
Actually it's just one root error (`java.lang.IllegalArgumentException: Could not resolve placeholder 'gameyfin.sources' in value "#{'${gameyfin.sources}'.split(',')[0]}"`) and the other three errors are just consequences of it.
Anyway, try replacing this: `gameyfin.sources=C:\Users\gnofl\Documents\Gameyfin`
with this: `gameyfin.sources=C:\\Users\\gnofl\\Documents\\Gameyfin` and tell me if it worked 🙂

**Comment by notdeers** [comment]
Thanks for the fast reply!
I tried changing it to all three of `gameyfin.sources=C:\\Users\\gnofl\\Documents\\Gameyfin` , `gameyfin.sources=C:\\Gameyfin` and `gameyfin.sources=C:\\Gameyfin,C:\\Users\\gnofl\\Documents\\Gameyfin` and all 3 still gave the same error while trying to run the .jar file through command line.

Fully on accident while trying to open the properties file again, I double clicked the .jar file which opened, asked for JDK permission to run, and then started with no problems, and the localhost:8080 is now accessible and running fine. I honestly thought command line was the only way to run it, so now I'm just left with confusion as to why it can use the file path when running through double-click, but not through command line. My only idea is you mentioned permissions in the set-up video, so maybe I had file permissions wrong for the command line run. I didn't run cmd as administrator, so I could possibly see that causing problems now that I think about it.

I'm unsure if the failure to get permissions from command line would still be considered a bug or not, so I'll leave this open for you to close, but as far as my problem is concerned I think it's resolved. Thanks for dealing with my inexperience!

**Comment by grimsi** [comment]
Yes, seems like file permission issues were the culprit.
And no worries, it was a pleasure to help!
Going to close this now.
